#!/bin/bash
# Testing xinitrc for running my wm in a separate X session rather than with Xephyr

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Load fonts, colors, etc
xsetroot -cursor_name left_ptr &
sudo xset +fp ~/.fonts/
sudo xrdb -merge ~/capstonewm/Xresources

# Map the CAPS key to be another CTRL
setxkbmap -layout us -option ctrl:nocaps

#sudo chmod -R 755 /usr/local/share/zsh/site-functions

# Run a compositor 
compton&

# Run a basic panel
/home/pjm/capstonewm/scripts/./barscript.sh | lemonbar -g 1366x16 -d -B "#232c33" -f "-benis-lemon-medium-r-normal--10-110-*-*-*-*-*-*" | sh &

# Load background from last session
sh ~/.fehbg & 

# Run the window manager
#exec /home/pjm/capstonewm/tilewm

